apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-cluster1
  namespace: default
  labels:
    app: zookeeper-cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-cluster1
  template:
    metadata:
      labels:
        app: zookeeper-cluster1
    spec:
      hostname: zookeeper-cluster1
      containers:
      - name: zookeeper-cluster1
        image: wurstmeister/zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster1
  namespace: default
  labels:
    app: zookeeper-cluster1
spec:
  type: NodePort
  selector:
    app: zookeeper-cluster1
  ports:
  - name: zookeeper-cluster1
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name: zookeeper-follower-cluster1
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: zookeeper-leader-cluster1
    protocol: TCP
    port: 3888
    targetPort: 3888

---


kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment-1
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      name: kafka
      labels:
        name : kafka

    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster1:2181
        - name: KAFKA_CREATE_TOPICS
          value: "myTopic1:1:1"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
        - name: KAFKA_LISTENERS
          value: "INSIDE://:9094,OUTSIDE://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://:9094,OUTSIDE://kafka1.default.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT" # not production-ready!
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    name : kafka
